# Generated by Django 2.2.16 on 2020-11-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_post', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Texto')),
                ('link_post', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enlace')),
                ('date_post', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('author_post', models.CharField(blank=True, max_length=20, null=True, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
                'ordering': ['date_post'],
            },
        ),
    ]
