# Generated by Django 2.2.16 on 2020-11-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_post',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Texto'),
        ),
    ]
