# Generated by Django 2.2.16 on 2020-11-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201104_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link_post',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace'),
        ),
    ]
